### ISSUE TITLE
cool project but the pyscript doesnt work

### ISSUE THREAD

**Issue by daUnknownCoder** [CarloCattano/workspacer#1]
> ./workspaced.py

```bash
Traceback (most recent call last):
  File "/home/daUnknownCoder/aur/workspacer/./workspaced.py", line 78, in <module>
    win = WorkspaceSelector()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/daUnknownCoder/aur/workspacer/./workspaced.py", line 43, in __init__
    self.num_rows = (num_workspaces + self.num_columns - 1) // self.num_columns
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~
ZeroDivisionError: integer division or modulo by zero
```
workspace-listener.sh is running in the background

**Comment by xircon** [comment]
Log out then in..  I had same issue.

**Comment by CarloCattano** [comment]
should be fixed now
